mysql:
  username: username
  password: password
  database: database
  host: localhost
  port: 3306

worlds:
  world1: 1m
  world2: 2m

settings:
  prefix: "&cWorldTimeout &8| &7"
  noPerms: "&cDu hast keine Berechtigung"
  actionbar:
    activated: true
    format: "&cZeit&8: ยง9%HOURS%h %MINUTES%m %SECONDS%s"
  time:
    expired: "&cZeit abgelaufen"
    command: "/spawn"